import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Button, Input } from '../components/form'


const Home: NextPage = () => {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center">
        <section className="w-full max-w-[400px] bg-gray-900 p-8 px-8 rounded-lg">
          <form>
            <h1 className='text-3xl text-gray-200 font-bold tracking-wide text-center mb-5'>
              SIGN IN
            </h1>
            <div className="mb-4">
              <div className="mb-4">
                <Input type="text" id="username" label="User Name" />
              </div>
              <div className="">
                <Input type="password" id="password"  label="Password" />
              </div>
            </div>
            
            <Button label="Sign In" onClick={() => router.push('/dashboard')} />
          </form>
        </section>
      </main>

    </div>
  )
}

export default Home
